Month 8/step 2
evlukas/react-burger pull request #5
Opened 2023-04-24 01:50 UTC by evlukas

2023-04-24 05:15 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
– Используете именованные функции селекторы
- `Dnd` работает хорошо
- Верно используете Redux Toolkit

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:

- Счетчик у ингредиентов всегда равен - 1. Необходимо, чтобы он изменялся в зависимости от того добавлен ингредиент в конструктор или нет.
- Необходимо, чтобы в сторе находились данные о текущем просматриваемом ингредиенте.
- Не используйте моковые данные
- при добавлении ингредиента в конструктор `id` нужно генерировать и передавать в экшене

Более подробно описание проблемы смотрите комментарии в pull request.

**Можно лучше**

- лучше хранить в отдельном поле выбранную булку и в отдельном поле массив с начинками бургера, это сильно облегчит работу со стором в следущем этапе

`const constructorInitialState = { bun: null, ingredients: []};`

- Если при выполнении запроса к Api в усилителе произошла ошибка, то содержимое хранилища соответствующего элемента необходимо приводить к начальному состоянию. Например, если пользователь оформил заказ, а при оформлении второго у него произошла ошибка — в модальном окне не должен отображаться старый номер заказа. Аналогично при работе со списком ингредиентов.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-04-24 05:15 UTC, andryxxa93 commented on src/components/Burgerconstructor/BurgerConstructor.jsx
> +    let ingredientsId = [
**Можно лучше**

**здесь и далее в других местах** если переменная не перезаписывается её нужно объявлять как `const`, это помогает понять другим разработчикам, как мы будем использовать переменную, будем ли мы в коде перезаписывать её значение.
Так же стоит помнить, что добавление элемента в массив или изменение свойства объект не являются перезаписью самой переменной, а только изменяют его внутренне состояние и такие переменные так же объявляются как const

2023-04-24 05:15 UTC, andryxxa93 commented on src/services/slices/BurgerConstructorSlice.js
> +const data = [
**Необходимо исправить**
Использовать моковые данные не нужно. Данные на сервере могут измениться, необходимо подставлять данные получаемые с сервера

2023-04-24 05:15 UTC, andryxxa93 commented on src/services/slices/BurgerConstructorSlice.js
> +      newIngredient = {...newIngredient, id: uuid()}
**Надо исправить**

редьюсер должен быть чистой функции, сейчас при каждом вызове добавления ингредиента результат будет отличаться, даже если стейт и экшен одинаковые - будет генерироваться каждый раз новый id,  при добавлении ингредиента в конструктор id нужно генерировать и передавать в экшене, а не генерировать в редьюсере. Иначе это делает редьюсер не чистой функцией, что нарушает правило редьюсеров

2023-04-24 14:15 UTC, evlukas commented
Исправил все "нужно исправить", кроме счетчика, не смог воспроизвести "-1",  в консоли вижу что ingredientCounter всегда показывает актуальное значение, при добавлении и удалении ингредиента. Значение по умолчанию стоит 2

Пока не стал трогать замечания "можно лучше", но обязательно исправлю. Просто пока дедлайн горит )

Спасибо!

2023-04-25 06:51 UTC, andryxxa93 commented
- Вы немного неправильно поняли. Счетчик у ингредиентов должен отображать количество конкретного ингредиента добавленного в конструктор. Вот видите на скрине - булка добавлена, значит нужно увеличить счетчик. И так со всеми ингредиентами. 
<img width="730" alt="Снимок экрана 2023-04-25 в 09 50 38" src="https://user-images.githubusercontent.com/60173362/234196732-5bae8256-95cf-4047-af36-80f5f17e9eca.png">

2023-04-25 15:19 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-04-27 18:05 UTC, merged